name: Sikuli CI
# on push and on workflow dispatch we will trigger our code
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: macos-latest # the machine type
    strategy: # we are using strategy if we need to run on parallel with different devices and version
      matrix:
        api-level: [ 25 ] #Google api level for example [25,23,28]
        target: [ default ]
        #profile: ["Nexus 6", "Nexus 6P", "Nexus 9", "Nexus S", "Nexus 5X", "pixel_2", "pixel_c", "pixel_xl", "pixel_3a", "pixel_4_xl"]
        profile: ["Nexus 6", "Nexus 6P", "Nexus 9", "Nexus S", "Nexus 5X", "pixel_2", "pixel_c", "pixel_xl", "pixel_3a", "pixel_4_xl"]
      fail-fast: false

    steps:
      - name: checkout
        uses: actions/checkout@v2 #checkout the code

      - name: Download APK artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          # Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
          # Required, if artifact is from a different repo
          # Required, if repo is private a Personal Access Token with `repo` scope is needed
          github_token: ${{secrets.ACCESS_TOKEN}}
          # Required, workflow file name or ID
          workflow: main.yml
          # Optional, the status or conclusion of a completed workflow to search for
          # Can be one of a workflow conclusion:
          #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
          # Or a workflow status:
          #   "completed", "in_progress", "queued"
          workflow_conclusion: success
          # Optional, will get head commit SHA
          pr: ${{github.event.pull_request.number}}
          # Optional, no need to specify if PR is
          commit: ${{github.event.pull_request.head.sha}}
          # Optional, will use the branch
          branch: master
          # Optional, defaults to all types
          event: push
          # Optional, uploaded artifact name,
          # will download all artifacts if not specified
          # and extract them in respective subdirectories
          # https://github.com/actions/download-artifact#download-all-artifacts
          name: apk
          # Optional, directory where to extract artifact. Defaults to the artifact name (see `name` input)
          path: ./app
          # Optional, defaults to current repo
          repo: gabrielefantini/OmniNotesContinuousIntegration
          # Optional, check the workflow run whether it has an artifact
          # then will get the last available artifact from previous workflow
          # default false, just try to download from the last one
          check_artifacts: false

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 16

      - name: Giving Gradlew correct permissions
        run: chmod +x gradlew

      - name: Add X11
        run: |
          brew install --cask xquartz
          sudo /opt/X11/libexec/privileged_startx || true
        working-directory: .

      - name: Start Xvfb
        run: |
            PATH=$PATH:/opt/X11/bin
            Xvfb :1 &
            export DISPLAY=:1

      - name: Run Sikuli Tests
        uses: reactivecircus/android-emulator-runner@v2 # install and create the Emulator
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: ${{ matrix.profile }}
          emulator-options: -no-snapshot-save -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          enable-hw-keyboard: true
          script: bash InstallAPKandRunTests.sh

      - uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: /Users/runner/work/SikuliContinuousIntegration/SikuliContinuousIntegration/screenshots/

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.ethereal.email
          # Required mail server port:
          server_port: 587
          # Optional (recommended): mail server username:
          username: kyler.pfeffer83@ethereal.email
          # Optional (recommended) mail server password:
          password: q26wRdRveXFmUJHP7G
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: obiwan@example.com,yoda@example.com
          # Required sender full name (address can be skipped):
          from: Luke Skywalker # <user@example.com>
          # Optional HTML body read from file:
          html_body: file:///Users/runner/work/SikuliContinuousIntegration/SikuliContinuousIntegration/build/reports/tests/test/index.html

      - uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: /Users/runner/work/SikuliContinuousIntegration/SikuliContinuousIntegration/build/reports/tests/