name: Sikuli CI
on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 16

      - name: Giving Gradlew correct permissions
        run: chmod +x gradlew

      - name: Add X11
        run: |
          brew install --cask xquartz
          sudo /opt/X11/libexec/privileged_startx || true
        working-directory: .

      - name: Start Xvfb
        run: |
            PATH=$PATH:/opt/X11/bin
            Xvfb :0 -screen 0 1920x1080x24 &
            export DISPLAY=:0.0

      - name: Run Sikuli Tests
        uses: reactivecircus/android-emulator-runner@v2 # install and create the Emulator
        with:
          api-level: 29
          arch: x86_64
          profile: Nexus 6
          emulator-options: -no-snapshot-save -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: bash InstallAPKandRunTests.sh
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.ethereal.email
          # Required mail server port:
          server_port: 587
          # Optional (recommended): mail server username:
          username: kyler.pfeffer83@ethereal.email
          # Optional (recommended) mail server password:
          password: q26wRdRveXFmUJHP7G
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: obiwan@example.com,yoda@example.com
          # Required sender full name (address can be skipped):
          from: Luke Skywalker # <user@example.com>
          # Optional HTML body read from file:
          html_body: file:///Users/runner/work/SikuliContinuousIntegration/SikuliContinuousIntegration/build/reports/tests/test/index.html